[package]
name = "chwp"
version = "0.0.0" # will be replaced by the github actoin build script
authors = ["Rouven Himmelstein <rouven@himmelstein.info>"]
license = "MIT"
description = "Change your wallpaper from the command line interface."
readme = "README.md"
homepage = "https://github.com/RouHim/chwp-rust"
repository = "https://github.com/RouHim/chwp-rust"
keywords = ["cli", "wallpaper"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
serde_json = "1.0.82"   # String to json
rand = "0.8.5"          # Generate random
image = "0.24.2"        # Image processing (rotate, flip, ...)
dirs = "4.0.0"          # Platform-specific folder special detection, e.g. temp dir
ureq = "2.4.0"          # Http client library
winit = "0.26.1"        # To obtain monitor boundaries

# Strip debug symbols in release mode
[profile.release]
strip = "symbols"