[package]
name = "chwp"
version = "0.0.0" # will be replaced by the github actoin build script
authors = ["Rouven Himmelstein <rouven@himmelstein.info>"]
license = "MIT"
description = "Change your wallpaper from the command line interface."
readme = "README.md"
homepage = "https://github.com/RouHim/chwp-rust"
repository = "https://github.com/RouHim/chwp-rust"
keywords = ["cli", "wallpaper"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
serde_json = "1.0.82"
rand = "0.8.5"
image = "0.24.2"
dirs = "4.0.0"
ureq = "2.4.0"

# Strip debug symbols in release mode
[profile.release]
strip = "symbols"