[package]
name = "chwp"
version = "0.0.18"
authors = ["Rouven Himmelstein <rouven@himmelstein.info>"]
license = "GPL3"
description = "Change your wallpaper from command line"
readme = "README.md"
homepage = "https://github.com/RouHim/chwp-rust"
repository = "https://github.com/RouHim/chwp-rust"
keywords = ["cli", "wallpaper"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
serde_json = "1.0.79"
rand = "0.8.5"
image = "0.24.2"
dirs = "4.0.0"
reqwest = { version = "0.11.10", features = ["blocking"] }

# Strip debug symbols in release mode
[profile.release]
strip = "symbols"