[package]
name = "chwp-rust"
version = "0.1.0"
authors = ["Rouven Himmelstein <rouven@himmelstein.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
