jobs:
  build:
    docker:
      - image: cimg/rust:1.48
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - run: cargo build --release